version: 2

jobs:
  build:
    working_directory: ~/project

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-{{ .Branch }}
            - v1-master-{{ checksum "yarn.lock" }}
            - v1-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ~/project/node_modules
